### ISSUE TITLE
Getting items from player

### ISSUE THREAD

**Issue by Iwitrag** [IPVP-MC/canvas#1]
Hi, I really like the ability to select which actions can player do (like put items inside but donť take them out etc) - but I have problem with getting items which players put inside.

I have created simple empty ChestMenu and allowed putting items in. Then I created closeHandler for it which prints all slots.

But even if I put items inside this ChestMenu, when I get items from slots, all items are null.

How can I get items which I put inside ?

**Comment by sainttx** [comment]
This is tricky because the Menu interface itself only represents a template of what the inventory should look like for a player. I'm not yet sure what the best approach in terms of API design would be to include methods to fetch the raw item in a players currently opened menu.

I can think of a dirty solution where you could potentially access the Bukkit Inventory by using `org.bukkit.entity.Player#getOpenInventory` and click the raw slots, however this is unsupported and may cause some issues when working with the API.

Keep in mind that when you open a menu with Menu.open, it may overwrite any items that a player added to the menu. I'll see if I can play with this and come up with some mechanism when I have some spare time.

**Comment by geox25** [comment]
Sorry to revive this issue, but I am having the same problem. Is there a proper way of doing this now?

**Comment by sainttx** [comment]
> Sorry to revive this issue, but I am having the same problem. Is there a proper way of doing this now?

Hey @geox25, you can use the `Slot#getRawItem` method to directly retrieve the item in the inventory. If you’re using a click handler and want to get the item being taken out, you can also now use the `ClickInformation#isTakingItem`, `ClickInformation#getTakingItem`, and `ClickInformation#getTakingItemAmount` methods to help with this.
