### ISSUE TITLE
Menu gets "lost" when opening from another menu

### ISSUE THREAD

**Issue by muelleel** [IPVP-MC/canvas#20]
Hello,
i have following test-code which showcases my problem:

```
Menu test = ChestMenu.builder(1).build();
test.getSlot(0).setItem(new ItemStack(Material.GRASS_BLOCK));

Menu test2 = ChestMenu.builder(6).build();
test2.getSlot(5).setItem(new ItemStack(Material.DIAMOND));

test.setCloseHandler(((player, menu) -> {
        test2.open(player);
}));

test2.setCloseHandler(((player, menu) -> {
        test.open(player);
}));

test.open(e.getPlayer());
```

I would expect that both Inventories are alternating when closing them and both Items in both Menu's are not movable. But what happens here is that after the first close, the diamond-item is free movable and the closeHandler is not executed for the second Inventory. The first one works just fine.

am I using something wrong?
any ideas on this? 
Thanks!

**Comment by Mr-EmPee** [comment]
Heya @muelleel, I've debugged the code and found out an interesting thing.

Apparently, the closeHandler gets processed before the server has completed all the cleaning operation performed when closing an inventory. This implies that after you have opened the new inventory, the server completes the cleaning operations.

The 'cleaning operations' that I mentioned are quite important because they erase a value that tells which inventory is currently open. So yes, the server thinks that the player is not viewing any inventory, when instead it's not that way.

A fix would be to delay by 1 tick the execution of the close handler after the inventory is closed. If you don't want to mess with the code, you can use this workaround

<pre><code>
                    Menu test = ChestMenu.builder(1).build();
                    test.getSlot(0).setItem(new ItemStack(Material.GRASS_BLOCK));

                    Menu test2 = ChestMenu.builder(6).build();
                    test2.getSlot(5).setItem(new ItemStack(Material.DIAMOND));

                    test.setCloseHandler(((player, menu) -> {
                        Bukkit.getScheduler().runTaskLater(
                                plugin, () -> test2.open(player), 2
                        );
                    }));

                    test2.setCloseHandler(((player, menu) -> {
                        Bukkit.getScheduler().runTaskLater(
                                plugin, () -> test.open(player), 2
                        );
                    }));

                    test.open(SourceConverter.player(c));
</code></pre>

**Comment by muelleel** [comment]
thanks for looking through the code
yes, that works fine, thanks for the tip.
I had to do something similar when opening the menu, because otherwise the server also complained that it could not create the close listener...
makes sense to use that - thanks
